name: user_profile_shared_preferences_example
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  carousel_slider: ^4.0.0
  easy_splash_screen: ^1.0.3
  # switch animation between light and dark theme
  animated_theme_switcher: ^2.0.1-nullsafety.0
  auto_size_text: ^3.0.0
  # fluttertoast: ^8.0.9
  platform: ^3.1.0
  url_launcher: ^6.0.0-nullsafety
  # persist locally data
  shared_preferences: ^2.0.5

  # pick image
  image_picker: ^0.8.4+8


  # store image
  path_provider: ^2.0.1
  grouped_checkbox: ^1.0.0

  # firebase
  firebase_core: ^1.17.0
  cloud_firestore: ^3.1.17
  firebase_storage: ^10.0.3
  firebase_auth: ^3.3.9

  #stateMangement
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Popins
      fonts:
        - asset: assets/fonts/popins_regular.ttf
        - asset: assets/fonts/popins_light.ttf
          weight: 300
        - asset: assets/fonts/popins_bold.ttf
          weight: 700
        - asset: assets/fonts/popins_semibold.ttf
          weight: 600
        - asset: assets/fonts/popins_medium.ttf
          weight: 500
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages